### ISSUE TITLE
remove basic_configs for compatibility with solr >= 7

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/parasolr#48]
Versions of solr >= 7 no longer provide the `basic_configs` configset for use as a default. Instead, the `_default` configset should be used for this purpose. For more information, see: https://lucene.apache.org/solr/guide/7_0/major-changes-in-solr-7.html#new-default-configset ﻿

**Comment by rlskoeser** [comment]
This was resolved in PR #53
