### ISSUE TITLE
solr looks for configsets in wrong directory

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/parasolr#49]
this problem may be isolated to docker deployments; see: https://issues.apache.org/jira/browse/SOLR-7323

when creating a core, solr seems to look to `/var/solr/configsets`, but the `_default` configset is actually stored at `/opt/solr/server/solr/configsets`. this interacts with `SOLR_HOME`; if the variable is set to point at `opt/solr/server/solr` the core will instead fail because the directory isn't writable by solr (guesswork).

@kmcelwee and I were using 
```sh
docker run -d -p 8983:8983 -e "SOLR_HOME=/opt/solr/server/solr" solr:latest
```
to start a local instance.

**Comment by rlskoeser** [comment]
this is an issue with solr8 docker image, not parasolr, as indicated by the jira link; work around implemented and working in github actions build
