### ISSUE TITLE
Parasolr doesn't find model indexable subclass 

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/parasolr#59]
**Describe the bug**
(Django 3.1) The class meta value `abstract` is displayed as `True`, despite being explicitly defined as `False`. This may come from a new Django version

**To reproduce**
See PR https://github.com/Princeton-CDH/geniza/pull/151

Blocking https://github.com/Princeton-CDH/geniza/issues/93

**Comment by rlskoeser** [comment]
resolved by #60
