### ISSUE TITLE
Provides Django management command to index models that subclass Indexable and other non-model content.  

### ISSUE THREAD

**Issue by meg-codes** [Princeton-CDH/parasolr#8]
## dev notes
- [x] Should be possible to auto detect models that extend Indexable and add flags to index or clear just those records
- [ ] ~Adapt PPA logic for pages to allow a pseudo-document/model and arbitrary indexing procedure~

**Comment by rlskoeser** [comment]
Postponing figuring out how to support indexing content like PPA pages which are not models.

**Comment by rlskoeser** [comment]
Working in QA for s&co
